name: Shutdown Railway Bot

on:
  schedule:
    - cron: '30 0 * * 1-5'  # 8:30 AM PHT = 00:30 UTC
  workflow_dispatch:

jobs:
  shutdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout shutdown branch
        uses: actions/checkout@v3
        with:
          ref: shutdown-branch

      - name: Trigger Railway Deploy with shutdown code
        run: |
          curl -X POST https://backboard.railway.app/project/44133da1-37fc-4175-807f-610146cbec73/deploy \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}"
