name: Wake Railway Bot

on:
  schedule:
    # 7:30 AM PH time = 11:30 PM UTC, Mon–Fri
    - cron: '30 23 * * 1-5'
  workflow_dispatch: # allows manual runs

jobs:
  wake_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway Deploy
        run: |
          curl -X POST https://backboard.railway.app/project/44133da1-37fc-4175-807f-610146cbec73/deploy \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}"
